language: php

sudo: false

addons:
  apt:
    packages:
    - php5-cgi
    - php5-mysql

php:
  - 5.4
  - 5.5
  - 5.6

mysql:
  database: restful
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - pwd
  - cd ../..
  - pwd

  # install drush
  - composer self-update
  - composer global require --no-interaction "drush/drush:7.*"
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database restful'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/restful --enable=simpletest

  # reference and enable restful in build site
  - echo $TRAVIS_BUILD_DIR
  - ls restful/drupal/sites/all/modules
  - ln -s $TRAVIS_BUILD_DIR restful/drupal/sites/all/modules/restful
  - cd restful/drupal
  - drush dl registry_rebuild
  - drush --yes pm-enable plug
  - drush rr
  - drush --yes pm-enable restful restful_token_auth restful_test

  # Download entity validator.
  - drush dl entity_validator --dev --yes

  # Patch Entity API.
  - cd sites/all/modules/entity
  - curl -O https://www.drupal.org/files/issues/2086225-entity-access-check-18.patch
  - patch -p1 < 2086225-entity-access-check-18.patch
  - cd -

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run RESTful --uri=http://127.0.0.1:8080
